<a href="https://colab.research.google.com/github/runyiakoso/FoodXplora-Runyi/blob/master/Numpy_%26_pandas_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
rand = np.random.rand(5)
print(rand)
rand3 = np.random.randn(5,5)
print(rand3)
print(rand3[0:2,1:3])
print('Values greater than 0:', rand3[rand3>0])
print('Values less than 0:', rand3[rand3<0])
'''rand1 = np.random.rand(5,3)
print(rand1)
rand2 = np.random.randn(5) #n - normal distribution, mean 0 variance 1
print(rand2)
rand3 = np.random.randn(5,5)
print(rand3)
print('Mean:', np.mean(rand2))
print('Std:', np.std(rand2))
rand3 = np.random.randint(1,5,10) #1-low, 5-high, 10-size or shape of output
print(rand3)
rand4 = np.random.randint(1,5,[5,5])# the [5,5] is matrix
print(rand4)

#access entries in Numpy array
print(rand[3])
print(rand[0:3])
print(rand[0:5:2])

#to access indexes to np array, use np.arange[]
print(rand[np.arange(1,5,2)])
'''
#accessing using logical operations

print('Values greater than 0.5: ', rand[rand>0.5])
print('Values less than 0.5: ', rand[rand<0.5])


[0.02535297 0.50743636 0.04174423 0.61211196 0.76547843]
[[ 0.58961003  0.65576902  0.10392008 -1.52622411 -0.04198263]
 [-0.79023974 -1.57500975  0.04196663 -1.63517427  0.77502145]
 [ 0.04091046  1.11898139 -0.90513385  0.45263667  1.22680099]
 [-0.86676522  1.34129453  0.33801612 -2.19274235 -0.17549789]
 [-0.73780117  0.68513567  0.69656412  0.39460993 -1.23608289]]
[[ 0.65576902  0.10392008]
 [-1.57500975  0.04196663]]
Values greater than: [0.58961003 0.65576902 0.10392008 0.04196663 0.77502145 0.04091046
 1.11898139 0.45263667 1.22680099 1.34129453 0.33801612 0.68513567
 0.69656412 0.39460993]
Values less than: [-1.52622411 -0.04198263 -0.79023974 -1.57500975 -1.63517427 -0.90513385
 -0.86676522 -2.19274235 -0.17549789 -0.73780117 -1.23608289]
Values greater than 0.5:  [0.50743636 0.61211196 0.76547843]
Values less than 0.5:  [0.02535297 0.04174423]


In [ ]:
rand>0.5

array([ True, False, False,  True,  True])

In [ ]:
rand3 = np.random.randn(5,5)
print(rand3[1]) #row 1 is 0,row 2 is 1, row 3 is 2, etc
print(rand3[1][2])#means row index 1, column index 2 - to access individual matrix

[[-1.12982629 -0.86200527]
 [-0.46149495  0.56494199]]
[-0.22994349 -0.46149495  0.56494199 -0.94412721 -1.10391913]
0.5649419911446345


In [ ]:
rand[0:3] = 4
print(rand)
rand[3:5]= [5,6]
print(rand)



[4.         4.         4.         0.61211196 0.76547843]
[4. 4. 4. 5. 6.]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])


5


In [9]:
import numpy as np
matrix3 =np.array([[1, 3, 5, 8, 9],
    [7, 6, 1, 2, 4],
    [3, 5, 9, 7, 6]])
print(matrix3)
sub_mat = matrix3[0:2, 1:3].copy() #the copy method will not let the changes made in sub_array reflect in the main array
print(sub_mat)
sub_mat[:] = 7 #changes all values in sub mat to 7
print(sub_mat)

[[1 3 5 8 9]
 [7 6 1 2 4]
 [3 5 9 7 6]]
[[3 5]
 [6 1]]
[[7 7]
 [7 7]]


In [ ]:
matrix3[1:3,1:4] =0 #index 1,3 i.e 2nd row - 3rd row, index 1:4 i.e 2nd column - 4th column (counting from 1 not o)
print('Matrix after modification: \n', matrix3)


In [12]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [21]:
rand_num = np.random.randint(1,10,10).reshape(2,5)
print(rand_num)
print("")
rand_num2 = np.random.randint(12,24,12).reshape(2,6)
print(rand_num2)

[[7 8 4 4 6]
 [2 8 8 7 5]]

[[15 16 19 23 20 17]
 [23 17 21 23 22 13]]


In [22]:
np.save('Saved num array',  rand_num)


In [7]:
import numpy as np
rand_num = np.random.randint(1,10,10).reshape(2,5)
print(rand_num)
print("")
rand_num2 = np.random.randint(12,24,12).reshape(2,6)
print(rand_num2)
np.savez('/content/drive/myDrive/Colab Notebooks/saved_file_names.npz', rand_num=rand_num, rand_num2=rand_num2)

[[3 8 9 5 8]
 [3 8 4 1 5]]

[[17 23 22 14 21 22]
 [18 15 18 23 16 23]]


FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/myDrive/Colab Notebooks/saved_file_names.npz'

In [ ]:
loaded_arr = np.load('çontent/drive/myDrive/Colab_Notebooks/saved_file_names.npy')
loaded_multi = np.load ('/content/drive/myDrive/Colab Notebooks/multiple_file_names.npz')
print(loaded_arr)
print(loaded_multi)

print('1st matrix: \n ', loaded_multi['rand_num'])
print('2nd matrix: \n ', loaded_multi['rand_num2'])

In [ ]:
#we can also save them as text files.. especially if we want to open them with excel, R or other programming languages
np.savetxt('çontent/drive/myDrive/Colab_Notebooks/text_file_names.txt', rand_num, delimiter=',')#delimiter means what comes between the elements, is it comma or??
rand_num_txt = np.loadtxt ('/content/drive/myDrive/Colab Notebooks/text_file_names.txt', delimiter=',')

print(rand_num)
print(rand_num_txt)
